### ISSUE TITLE
Dawn version does not compile

### ISSUE THREAD

**Issue by jswalens** [ligeroinc/ligero-prover#3]
When I try to compile the Dawn version used in the README (`git checkout cec4482eccee45696a7c0019e750c77f101ced04`), I get an error about the symbol `HashCode` being redefined:

```
[ 41%] Building CXX object src/tint/CMakeFiles/tint_api_common.dir/api/common/vertex_pulling_config.cc.o
In file included from /home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:34,
                 from /home/jw/dawn/src/tint/api/common/vertex_pulling_config.cc:28:
/home/jw/dawn/src/tint/utils/reflection.h:209:14: error: declaration of ‘tint::HashCode tint::VertexAttributeDescriptor::HashCode() const’ changes meaning of ‘HashCode’ [-Wchanges-meaning]
  209 |     HashCode HashCode() const {                               \
      |              ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:98:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
   98 |     TINT_REFLECT_HASH_CODE(VertexAttributeDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:5: note: used here to mean ‘using tint::HashCode = uint32_t’
  209 |     HashCode HashCode() const {                               \
      |     ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:98:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
   98 |     TINT_REFLECT_HASH_CODE(VertexAttributeDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jw/dawn/src/tint/utils/rtti/castable.h:39,
                 from /home/jw/dawn/src/tint/utils/containers/slice.h:37,
                 from /home/jw/dawn/src/tint/utils/containers/vector.h:40,
                 from /home/jw/dawn/src/tint/utils/reflection.h:37:
/home/jw/dawn/src/tint/utils/math/hash.h:63:7: note: declared here
   63 | using HashCode = uint32_t;
      |       ^~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:14: error: declaration of ‘tint::HashCode tint::VertexBufferLayoutDescriptor::HashCode() const’ changes meaning of ‘HashCode’ [-Wchanges-meaning
]
  209 |     HashCode HashCode() const {                               \
      |              ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:122:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  122 |     TINT_REFLECT_HASH_CODE(VertexBufferLayoutDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:5: note: used here to mean ‘using tint::HashCode = uint32_t’
  209 |     HashCode HashCode() const {                               \
      |     ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:122:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  122 |     TINT_REFLECT_HASH_CODE(VertexBufferLayoutDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/math/hash.h:63:7: note: declared here
   63 | using HashCode = uint32_t;
      |       ^~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:14: error: declaration of ‘tint::HashCode tint::VertexPullingConfig::HashCode() const’ changes meaning of ‘HashCode’ [-Wchanges-meaning]
  209 |     HashCode HashCode() const {                               \
      |              ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:137:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  137 |     TINT_REFLECT_HASH_CODE(VertexPullingConfig);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:5: note: used here to mean ‘using tint::HashCode = uint32_t’
  209 |     HashCode HashCode() const {                               \
      |     ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:137:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  137 |     TINT_REFLECT_HASH_CODE(VertexPullingConfig);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/math/hash.h:63:7: note: declared here
   63 | using HashCode = uint32_t;
      |       ^~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-documentation-unknown-command’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-nrvo’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-deprecated-builtins’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-assume’ may have been intended to silence earlier diagnostics
```

This is apparently a known issue when building with GCC, that was fixed in Dawn in commit [e4ea4152a0e3002a6b43dc6f475a935c6511fd31](https://dawn.googlesource.com/dawn/+/e4ea4152a0e3002a6b43dc6f475a935c6511fd31). I can confirm that with

```
git checkout cec4482eccee45696a7c0019e750c77f101ced04
git cherry-pick e4ea4152a0e3002a6b43dc6f475a935c6511fd31
```

I can successfully compile Dawn and use it to build Ligetron.

**Comment by gmrehbein** [comment]
@jswalens What version of gcc and which platform? 

Try:

```
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DDAWN_FETCH_DEPENDENCIES=ON \
    -DDAWN_ENABLE_INSTALL=ON \
    -DDAWN_USE_GLFW=OFF \
    -DDAWN_BUILD_SAMPLES=OFF \
    -DTINT_BUILD_BENCHMARKS=OFF \
    -DTINT_BUILD_IR_BINARY=OFF \
    -DTINT_BUILD_FUZZERS=OFF \
    -DTINT_BUILD_TESTS=OFF \
    -DTINT_BUILD_CMD_TOOLS=OFF
```

this works on Ubuntu 24.04 and gcc 13.3.0

**Comment by jswalens** [comment]
No, I still get the same result. I'm running Ubuntu 24.04 in a VM on macOS, and I'm also using gcc 13.3.0:

```
$ uname -a
Linux ubuntu-vm 6.8.0-86-generic #87-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 22 17:54:31 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.3 LTS
Release:	24.04
Codename:	noble
$ g++ --version
g++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
```

```
$ git checkout cec4482eccee45696a7c0019e750c77f101ced04
$ mkdir release && cd release
$ cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DDAWN_FETCH_DEPENDENCIES=ON \
    -DDAWN_ENABLE_INSTALL=ON \
    -DDAWN_USE_GLFW=OFF \
    -DDAWN_BUILD_SAMPLES=OFF \
    -DTINT_BUILD_BENCHMARKS=OFF \
    -DTINT_BUILD_IR_BINARY=OFF \
    -DTINT_BUILD_FUZZERS=OFF \
    -DTINT_BUILD_TESTS=OFF \
    -DTINT_BUILD_CMD_TOOLS=OFF ..
$ make
[...]
In file included from /home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:34,
                 from /home/jw/dawn/src/tint/api/common/vertex_pulling_config.cc:28:
/home/jw/dawn/src/tint/utils/reflection.h:209:14: error: declaration of ‘tint::HashCode tint::VertexAttributeDescriptor::HashCode() const’ changes meaning of ‘HashCode’ [-Wchanges-meaning]
  209 |     HashCode HashCode() const {                               \
      |              ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:98:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
   98 |     TINT_REFLECT_HASH_CODE(VertexAttributeDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:5: note: used here to mean ‘using tint::HashCode = uint32_t’
  209 |     HashCode HashCode() const {                               \
      |     ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:98:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
   98 |     TINT_REFLECT_HASH_CODE(VertexAttributeDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jw/dawn/src/tint/utils/rtti/castable.h:39,
                 from /home/jw/dawn/src/tint/utils/containers/slice.h:37,
                 from /home/jw/dawn/src/tint/utils/containers/vector.h:40,
                 from /home/jw/dawn/src/tint/utils/reflection.h:37:
/home/jw/dawn/src/tint/utils/math/hash.h:63:7: note: declared here
   63 | using HashCode = uint32_t;
      |       ^~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:14: error: declaration of ‘tint::HashCode tint::VertexBufferLayoutDescriptor::HashCode() const’ changes meaning of ‘HashCode’ [-Wchanges-meaning]
  209 |     HashCode HashCode() const {                               \
      |              ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:122:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  122 |     TINT_REFLECT_HASH_CODE(VertexBufferLayoutDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:5: note: used here to mean ‘using tint::HashCode = uint32_t’
  209 |     HashCode HashCode() const {                               \
      |     ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:122:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  122 |     TINT_REFLECT_HASH_CODE(VertexBufferLayoutDescriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/math/hash.h:63:7: note: declared here
   63 | using HashCode = uint32_t;
      |       ^~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:14: error: declaration of ‘tint::HashCode tint::VertexPullingConfig::HashCode() const’ changes meaning of ‘HashCode’ [-Wchanges-meaning]
  209 |     HashCode HashCode() const {                               \
      |              ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:137:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  137 |     TINT_REFLECT_HASH_CODE(VertexPullingConfig);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/reflection.h:209:5: note: used here to mean ‘using tint::HashCode = uint32_t’
  209 |     HashCode HashCode() const {                               \
      |     ^~~~~~~~
/home/jw/dawn/src/tint/api/common/vertex_pulling_config.h:137:5: note: in expansion of macro ‘TINT_REFLECT_HASH_CODE’
  137 |     TINT_REFLECT_HASH_CODE(VertexPullingConfig);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/jw/dawn/src/tint/utils/math/hash.h:63:7: note: declared here
   63 | using HashCode = uint32_t;
      |       ^~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-documentation-unknown-command’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-nrvo’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-deprecated-builtins’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-assume’ may have been intended to silence earlier diagnostics
make[2]: *** [src/tint/CMakeFiles/tint_api_common.dir/build.make:79: src/tint/CMakeFiles/tint_api_common.dir/api/common/vertex_pulling_config.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7576: src/tint/CMakeFiles/tint_api_common.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

As said above, this seems to be a known issue in Dawn that was fixed [here](https://dawn.googlesource.com/dawn/+/e4ea4152a0e3002a6b43dc6f475a935c6511fd31). By cherry-picking that commit, I can fix the issue.
